FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
    bird \
    && yum clean all \
    && rm -f /etc/bird.conf

{% elif base_distro in ['ubuntu'] %}

RUN echo "deb http://ppa.launchpad.net/cz.nic-labs/bird/ubuntu $(lsb_release -sc)  main" > /etc/apt/sources.list.d/bird.list \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 52463488670E69A092007C24F2331238F9C59A45 \
    && apt-get update \
    && apt-get -y install --no-install-recommends bird \
    && apt-get clean \
    && rm -f /etc/bird/bird.conf \
    && mkdir -p /var/run/bird \
    && chown bird:bird /var/run/bird

{% elif base_distro in ['debian'] %}

RUN wget -O - http://bird.network.cz/debian/apt.key | apt-key add - \
    && apt-get install --no-install-recommends lsb-release \
    && echo "deb http://bird.network.cz/debian/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/bird.list \
    && apt-get update \
    && apt-get install --no-install-recommends bird \
    && rm -f /etc/bird/bird.conf \
    && mkdir -p /var/run/bird \
    && chown bird:bird /var/run/bird

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}

USER root
