FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

{% elif base_distro in ['debian'] %}

{% elif base_distro in ['ubuntu'] %}

RUN echo "deb http://ppa.launchpad.net/project-calico/calico-1.4/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/calico.list \
    && apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 71e607a24ddae8581987b54167d7e35b3d40a6a7 \
    && apt-get update  \
    && apt-get -y install --no-install-recommends \
       calico-felix \
       python-setuptools \
    && apt-get clean

{% endif %}

COPY felix_sudoers /etc/sudoers.d/felix_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN useradd --user-group felix \
    && chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/felix_sudoers \
    && usermod -a -G kolla felix

{{ include_footer }}

USER root
